services:
  evrinoma.partner.constraint.property.name:
    class: Evrinoma\PartnerBundle\Constraint\Property\Name

  evrinoma.partner.constraint.property.url:
    class: Evrinoma\PartnerBundle\Constraint\Property\Url

  evrinoma.partner.constraint.property.active:
    class: Evrinoma\PartnerBundle\Constraint\Property\Active

  evrinoma.partner.constraint.property.logo:
    class: Evrinoma\PartnerBundle\Constraint\Property\Logo

  evrinoma.partner.constraint.property.title:
    class: Evrinoma\PartnerBundle\Constraint\Property\Title